-- MySQL Script generated by MySQL Workbench
-- Tue Jun 17 14:45:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `Num_Client` INT NOT NULL,
  `NOM` VARCHAR(45) NOT NULL,
  `PRENOM` VARCHAR(45) NOT NULL,
  `DATE INSCRIPTION` DATE NULL,
  `ADRESSE` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`Num_Client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categories de produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categories de produit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categories de produit` (
  `idCategories` INT NOT NULL,
  `NOM` VARCHAR(45) NOT NULL,
  `DESCRIPTIF` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produits` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produits` (
  `idProduits` INT NOT NULL,
  `NOM` VARCHAR(45) NULL,
  `DATE PEREMPTION` VARCHAR(45) NULL,
  `PHOTO` VARCHAR(45) NULL,
  `MARQUE` VARCHAR(45) NULL,
  `PRIX` DECIMAL NULL,
  `idCategories` INT NULL,
  `Categories de produit_idCategories` INT NOT NULL,
  PRIMARY KEY (`idProduits`),
  INDEX `fk_Produits_Categories de produit1_idx` (`Categories de produit_idCategories` ASC) VISIBLE,
  CONSTRAINT `fk_Produits_Categories de produit1`
    FOREIGN KEY (`Categories de produit_idCategories`)
    REFERENCES `mydb`.`Categories de produit` (`idCategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commandes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Commandes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Commandes` (
  `Num_Commande` INT NOT NULL,
  `DATE` DATE NULL,
  `Clients_Num_Client` INT NOT NULL,
  PRIMARY KEY (`Num_Commande`),
  INDEX `fk_Commandes_Clients_idx` (`Clients_Num_Client` ASC) VISIBLE,
  CONSTRAINT `fk_Commandes_Clients`
    FOREIGN KEY (`Clients_Num_Client`)
    REFERENCES `mydb`.`Clients` (`Num_Client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detail_Commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Detail_Commande` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Detail_Commande` (
  `idDetail_Commande` INT NOT NULL,
  `Num_Commande` INT NULL,
  `idProduits` INT NULL,
  `Quantite` INT NULL,
  `Commandes_Num_Commande` INT NOT NULL,
  `Produits_idProduits` INT NOT NULL,
  PRIMARY KEY (`idDetail_Commande`),
  INDEX `fk_Detail_Commande_Commandes1_idx` (`Commandes_Num_Commande` ASC) VISIBLE,
  INDEX `fk_Detail_Commande_Produits1_idx` (`Produits_idProduits` ASC) VISIBLE,
  CONSTRAINT `fk_Detail_Commande_Commandes1`
    FOREIGN KEY (`Commandes_Num_Commande`)
    REFERENCES `mydb`.`Commandes` (`Num_Commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detail_Commande_Produits1`
    FOREIGN KEY (`Produits_idProduits`)
    REFERENCES `mydb`.`Produits` (`idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
